### ISSUE TITLE
Generator throws error if project is in subdirectory

### ISSUE THREAD

**Issue by jforaker** [johannesjo/angular-auto-admin-looopback#1]
1. I have my loopback project in `foo/api`
2. when I run `yo aaal` in the directory `foo/api` I get the error:  

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/Users/jakeforaker/dev/foo/common/models'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.getModelData (/usr/local/lib/node_modules/generator-aaal/helper.js:129:20)
    at Object.module.exports.createFiles (/usr/local/lib/node_modules/generator-aaal/crud-gen.js:37:39)
    at module.exports.yeoman.Base.extend.runCrudGenerator (/usr/local/lib/node_modules/generator-aaal/app/index.js:66:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-aaal/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-aaal/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-aaal/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-aaal/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

I suspect its because the generator checks the root __dirname or something.

Is there way around this?

**Comment by jforaker** [comment]
Ahh I had to remove my existing `yo-rc.json` file, then it worked. (Though curious because it was empty object  `{}`)

**Comment by johannesjo** [comment]
Thanks for reporting the issue.  I look into it this Friday.
